
ton:
#  net-config: classpath:global-config.json
  net-config: classpath:testnet-global.config.json
  wallet:
    mnemonic: ${WALLET_MNEMONIC:"never gonna give you up never gonna let you down never gonna run around and desert you never gonna make you cry say goodbye"}
